name = "wishpocket"
compatibility_date = "2024-01-01"

# KV Namespace binding - This is required for data storage
# Run `npx wrangler kv:namespace create WISH_KV` to get the ID
[[kv_namespaces]]
binding = "WISH_KV"
id = "630ffb1316f94f4895116ed184e079a6"

[site]
bucket = "./build"
